spring.application.name=SevenElevenAPI
spring.datasource.url=jdbc:postgresql://dpg-d83ipa6k1jcs73bteq9g-a.oregon-postgres.render.com/seven11_dued
spring.datasource.username=seven11_user
spring.datasource.password=kwBln6NxA95rxKVihAyFJbz5AI7svqIK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080